[env:waveshare-esp32-s3-eth]
platform = espressif32 @ 6.7.0
framework = arduino
board = esp32-s3-devkitc-1

platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
    framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    dawidchyrzynski/home-assistant-integration@^2.1.0
    https://github.com/ze-conehead/SmartRC-CC1101-Driver-Lib

monitor_speed = 115200
