[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
lib_deps = 
	dawidchyrzynski/home-assistant-integration@^2.1.0
	https://github.com/ze-conehead/SmartRC-CC1101-Driver-Lib
monitor_speed = 115200
