name: Build firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run

      - name: Merge firmware
        run: |
          python -m pip install esptool
          python -m esptool merge-bin \
            --chip esp32s3 \
            --flash-mode qio \
            --flash-size 16MB \
            -o firmware-merged.bin \
            0x0 .pio/build/waveshare-esp32-s3-eth/bootloader.bin \
            0x8000 .pio/build/waveshare-esp32-s3-eth/partitions.bin \
            0xe000 .pio/build/waveshare-esp32-s3-eth/boot_app0.bin \
            0x10000 .pio/build/waveshare-esp32-s3-eth/firmware.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware-merged.bin
